export type McuId = 'teensy41' | 'esp32' | 'pico'

export interface PinRef {
  pin_number: string
  pin_function: string
  description: string
}

export interface McuLayout {
  label: string
  left: PinRef[]  // top → bottom (physical pins 1..N/2)
  right: PinRef[] // top → bottom (physical pins N..N/2+1)
}

export const MCU_OPTIONS = [
  { id: 'pico',     label: 'Raspberry Pi Pico' },
  { id: 'esp32',    label: 'ESP32 DevKit' },
  { id: 'teensy41', label: 'Teensy 4.1' },
  { id: 'custom',   label: 'Custom MCU' },
] as const

export const PIN_LAYOUTS: Record<McuId, McuLayout> = {
  pico: {
    label: 'Raspberry Pi Pico',
    left: [
      { pin_number: 'GP0',     pin_function: 'UART0_TX / SPI0_RX / I2C0_SDA',  description: 'PWM A0' },
      { pin_number: 'GP1',     pin_function: 'UART0_RX / SPI0_CSn / I2C0_SCL', description: 'PWM B0' },
      { pin_number: 'GND',     pin_function: 'Ground',                           description: '' },
      { pin_number: 'GP2',     pin_function: 'SPI0_SCK / I2C1_SDA',            description: 'PWM A1' },
      { pin_number: 'GP3',     pin_function: 'SPI0_TX / I2C1_SCL',             description: 'PWM B1' },
      { pin_number: 'GP4',     pin_function: 'UART1_TX / SPI0_RX / I2C0_SDA',  description: 'PWM A2' },
      { pin_number: 'GP5',     pin_function: 'UART1_RX / SPI0_CSn / I2C0_SCL', description: 'PWM B2' },
      { pin_number: 'GND',     pin_function: 'Ground',                           description: '' },
      { pin_number: 'GP6',     pin_function: 'SPI0_SCK / I2C1_SDA',            description: 'PWM A3' },
      { pin_number: 'GP7',     pin_function: 'SPI0_TX / I2C1_SCL',             description: 'PWM B3' },
      { pin_number: 'GP8',     pin_function: 'UART1_TX / SPI1_RX / I2C0_SDA',  description: 'PWM A4' },
      { pin_number: 'GP9',     pin_function: 'UART1_RX / SPI1_CSn / I2C0_SCL', description: 'PWM B4' },
      { pin_number: 'GND',     pin_function: 'Ground',                           description: '' },
      { pin_number: 'GP10',    pin_function: 'SPI1_SCK / I2C1_SDA',            description: 'PWM A5' },
      { pin_number: 'GP11',    pin_function: 'SPI1_TX / I2C1_SCL',             description: 'PWM B5' },
      { pin_number: 'GP12',    pin_function: 'UART0_TX / SPI1_RX / I2C0_SDA',  description: 'PWM A6' },
      { pin_number: 'GP13',    pin_function: 'UART0_RX / SPI1_CSn / I2C0_SCL', description: 'PWM B6' },
      { pin_number: 'GND',     pin_function: 'Ground',                           description: '' },
      { pin_number: 'GP14',    pin_function: 'SPI1_SCK / I2C1_SDA',            description: 'PWM A7' },
      { pin_number: 'GP15',    pin_function: 'SPI1_TX / I2C1_SCL',             description: 'PWM B7' },
    ],
    right: [
      { pin_number: 'VBUS',    pin_function: 'USB 5V',                          description: '5V from USB connector' },
      { pin_number: 'VSYS',    pin_function: 'System power',                    description: '1.8–5.5V main power in' },
      { pin_number: 'GND',     pin_function: 'Ground',                           description: '' },
      { pin_number: '3V3_EN',  pin_function: '3.3V enable',                     description: 'Drive low to disable regulator' },
      { pin_number: '3V3',     pin_function: '3.3V output',                     description: '300mA max' },
      { pin_number: 'ADC_REF', pin_function: 'ADC reference',                   description: 'Tie to 3V3 if unused' },
      { pin_number: 'GP28',    pin_function: 'ADC2 / SPI1_RX',                  description: 'ADC channel 2' },
      { pin_number: 'AGND',    pin_function: 'Analog ground',                   description: 'Connect near ADC inputs' },
      { pin_number: 'GP27',    pin_function: 'ADC1 / I2C1_SCL',                 description: 'ADC channel 1' },
      { pin_number: 'GP26',    pin_function: 'ADC0 / I2C1_SDA',                 description: 'ADC channel 0' },
      { pin_number: 'RUN',     pin_function: 'Reset (active low)',               description: 'Pull low to reset' },
      { pin_number: 'GP22',    pin_function: 'GPIO',                             description: 'PWM A11' },
      { pin_number: 'GND',     pin_function: 'Ground',                           description: '' },
      { pin_number: 'GP21',    pin_function: 'I2C0_SCL',                        description: 'PWM B10' },
      { pin_number: 'GP20',    pin_function: 'I2C0_SDA',                        description: 'PWM A10' },
      { pin_number: 'GP19',    pin_function: 'SPI0_TX / I2C1_SCL',             description: 'PWM B9' },
      { pin_number: 'GP18',    pin_function: 'SPI0_SCK / I2C1_SDA',            description: 'PWM A9' },
      { pin_number: 'GND',     pin_function: 'Ground',                           description: '' },
      { pin_number: 'GP17',    pin_function: 'UART0_RX / SPI0_CSn / I2C0_SCL', description: 'PWM B8' },
      { pin_number: 'GP16',    pin_function: 'UART0_TX / SPI0_RX / I2C0_SDA',  description: 'PWM A8' },
    ],
  },

  esp32: {
    label: 'ESP32 DevKit',
    left: [
      { pin_number: 'EN',    pin_function: 'Enable',                description: 'Pull low to reset' },
      { pin_number: 'IO36',  pin_function: 'ADC1_CH0 / SVP',        description: 'Input only; no pull resistors' },
      { pin_number: 'IO39',  pin_function: 'ADC1_CH3 / SVN',        description: 'Input only' },
      { pin_number: 'IO34',  pin_function: 'ADC1_CH6',              description: 'Input only' },
      { pin_number: 'IO35',  pin_function: 'ADC1_CH7',              description: 'Input only' },
      { pin_number: 'IO32',  pin_function: 'ADC1_CH4 / Touch9',    description: 'XTAL_32K_P; cap touch' },
      { pin_number: 'IO33',  pin_function: 'ADC1_CH5 / Touch8',    description: 'XTAL_32K_N' },
      { pin_number: 'IO25',  pin_function: 'ADC2_CH8 / DAC1',      description: 'DAC output 1' },
      { pin_number: 'IO26',  pin_function: 'ADC2_CH9 / DAC2',      description: 'DAC output 2' },
      { pin_number: 'IO27',  pin_function: 'ADC2_CH7 / Touch7',    description: 'PWM capable' },
      { pin_number: 'IO14',  pin_function: 'ADC2_CH6 / HSPI_CLK',  description: 'Touch6; boot strapping' },
      { pin_number: 'IO12',  pin_function: 'ADC2_CH5 / HSPI_MISO', description: 'Boot fail if high at reset' },
      { pin_number: 'GND',   pin_function: 'Ground',                description: '' },
      { pin_number: 'IO13',  pin_function: 'ADC2_CH4 / HSPI_MOSI', description: 'Touch4' },
      { pin_number: 'IO9',   pin_function: 'SPI_HD',               description: 'Tied to internal flash — avoid' },
      { pin_number: 'IO10',  pin_function: 'SPI_WP',               description: 'Tied to internal flash — avoid' },
      { pin_number: 'IO11',  pin_function: 'SPI_CS0',              description: 'Tied to internal flash — avoid' },
      { pin_number: '5V',    pin_function: 'VIN',                   description: '5V input or USB output' },
    ],
    right: [
      { pin_number: 'GND',   pin_function: 'Ground',                description: '' },
      { pin_number: '3V3',   pin_function: '3.3V output',           description: 'Max 1.1A from regulator' },
      { pin_number: 'IO15',  pin_function: 'ADC2_CH3 / HSPI_CS',   description: 'Touch3; boot strapping' },
      { pin_number: 'IO2',   pin_function: 'ADC2_CH2 / Touch2',    description: 'Built-in LED on DevKit; low at boot' },
      { pin_number: 'IO0',   pin_function: 'ADC2_CH1 / Touch1',    description: 'Boot mode; pull low for flash' },
      { pin_number: 'IO4',   pin_function: 'ADC2_CH0 / Touch0',    description: 'PWM capable' },
      { pin_number: 'IO16',  pin_function: 'UART2_RX',             description: 'Not usable with Bluetooth' },
      { pin_number: 'IO17',  pin_function: 'UART2_TX',             description: 'Not usable with Bluetooth' },
      { pin_number: 'IO5',   pin_function: 'VSPI_SS',              description: 'Must be high at reset' },
      { pin_number: 'IO18',  pin_function: 'VSPI_CLK',             description: 'SPI clock' },
      { pin_number: 'IO19',  pin_function: 'VSPI_MISO',            description: 'SPI MISO' },
      { pin_number: 'IO21',  pin_function: 'I2C_SDA',              description: 'Default I2C data line' },
      { pin_number: 'IO3',   pin_function: 'UART0_RX',             description: 'USB serial RX' },
      { pin_number: 'IO1',   pin_function: 'UART0_TX',             description: 'USB serial TX; debug output' },
      { pin_number: 'IO22',  pin_function: 'I2C_SCL',              description: 'Default I2C clock' },
      { pin_number: 'IO23',  pin_function: 'VSPI_MOSI',            description: 'SPI MOSI' },
    ],
  },

  teensy41: {
    label: 'Teensy 4.1',
    left: [
      { pin_number: '0',    pin_function: 'RX1',           description: 'UART1 RX; PWM; Touch' },
      { pin_number: '1',    pin_function: 'TX1',           description: 'UART1 TX; PWM; Touch' },
      { pin_number: '2',    pin_function: 'OUT2',          description: 'PWM; FlexPWM' },
      { pin_number: '3',    pin_function: 'LRCLK2',        description: 'PWM; I2S2 LRCLK' },
      { pin_number: '4',    pin_function: 'OUT1A',         description: 'PWM; I2S1' },
      { pin_number: '5',    pin_function: 'IN1A',          description: 'PWM; I2S1' },
      { pin_number: '6',    pin_function: 'OUT1B',         description: 'PWM; I2S1' },
      { pin_number: '7',    pin_function: 'RX2',           description: 'UART2 RX; Touch' },
      { pin_number: '8',    pin_function: 'TX2',           description: 'UART2 TX; Touch' },
      { pin_number: '9',    pin_function: 'OUT2B',         description: 'PWM; I2S2' },
      { pin_number: '10',   pin_function: 'SPI0_CS',       description: 'SPI0 CS; PWM' },
      { pin_number: '11',   pin_function: 'SPI0_MOSI',     description: 'SPI0 MOSI; PWM; Touch' },
      { pin_number: '12',   pin_function: 'SPI0_MISO',     description: 'SPI0 MISO; Touch' },
      { pin_number: '13',   pin_function: 'SPI0_SCK / LED',description: 'Built-in LED' },
      { pin_number: '14',   pin_function: 'A0 / TX3',      description: 'ADC; UART3 TX' },
      { pin_number: '15',   pin_function: 'A1 / RX3',      description: 'ADC; UART3 RX' },
      { pin_number: '16',   pin_function: 'A2 / RX4',      description: 'ADC; UART4 RX; Touch' },
      { pin_number: '17',   pin_function: 'A3 / TX4',      description: 'ADC; UART4 TX; Touch' },
      { pin_number: '18',   pin_function: 'A4 / I2C0_SDA', description: 'ADC; I2C0 SDA; Touch' },
      { pin_number: '19',   pin_function: 'A5 / I2C0_SCL', description: 'ADC; I2C0 SCL; Touch' },
      { pin_number: '20',   pin_function: 'A6 / TX5',      description: 'ADC; UART5 TX; Touch' },
      { pin_number: '21',   pin_function: 'A7 / RX5',      description: 'ADC; UART5 RX; Touch' },
      { pin_number: '22',   pin_function: 'A8',            description: 'ADC; PWM; Touch' },
      { pin_number: '23',   pin_function: 'A9',            description: 'ADC; PWM; Touch' },
      { pin_number: '3V3',  pin_function: '3.3V',          description: '~250mA regulated output' },
      { pin_number: 'GND',  pin_function: 'Ground',        description: '' },
      { pin_number: 'GND',  pin_function: 'Ground',        description: '' },
    ],
    right: [
      { pin_number: 'VIN',  pin_function: '5V input',      description: '3.6–5.5V; powers USB if >5V' },
      { pin_number: '3V3',  pin_function: '3.3V',          description: 'Regulated output' },
      { pin_number: '41',   pin_function: 'A17 / RX8',     description: 'ADC; UART8 RX; Touch' },
      { pin_number: '40',   pin_function: 'A16 / TX8',     description: 'ADC; UART8 TX; Touch' },
      { pin_number: '39',   pin_function: 'A15',           description: 'ADC; PWM' },
      { pin_number: '38',   pin_function: 'A14',           description: 'ADC; PWM' },
      { pin_number: '37',   pin_function: 'SPI2_CS',       description: 'SPI2 CS' },
      { pin_number: '36',   pin_function: 'SPI2_MOSI',     description: 'SPI2 MOSI' },
      { pin_number: '35',   pin_function: 'A13 / SPI2_MISO',description: 'ADC; SPI2 MISO' },
      { pin_number: '34',   pin_function: 'A12 / CAN3_TX', description: 'ADC; CAN3 TX' },
      { pin_number: '33',   pin_function: 'A11 / CAN3_RX', description: 'ADC; CAN3 RX' },
      { pin_number: '32',   pin_function: 'A12',           description: 'Analog only (lower res)' },
      { pin_number: '31',   pin_function: 'SPI1_CS',       description: 'SPI1 CS' },
      { pin_number: '30',   pin_function: 'SPI1_MOSI',     description: 'SPI1 MOSI' },
      { pin_number: '29',   pin_function: 'SPI1_MISO',     description: 'SPI1 MISO' },
      { pin_number: '28',   pin_function: 'RX7',           description: 'UART7 RX; Touch' },
      { pin_number: '27',   pin_function: 'TX7',           description: 'UART7 TX; Touch' },
      { pin_number: '26',   pin_function: 'A10',           description: 'Analog only' },
      { pin_number: '25',   pin_function: 'A11 / TX8',     description: 'ADC; UART8 TX; Touch' },
      { pin_number: '24',   pin_function: 'A10',           description: 'ADC; Touch' },
      { pin_number: 'GND',  pin_function: 'Ground',        description: '' },
      { pin_number: 'GND',  pin_function: 'Ground',        description: '' },
      { pin_number: 'GND',  pin_function: 'Ground',        description: '' },
      { pin_number: 'GND',  pin_function: 'Ground',        description: '' },
      { pin_number: 'GND',  pin_function: 'Ground',        description: '' },
    ],
  },
}
